# درجة الشفافية (0.0 شفاف بالكامل، 1.0 معتم بالكامل)
background_opacity 0

# التأكد إن الـ Blur مطفي (احتياطاً)
background_blur 0


# BEGIN_KITTY_THEME
# Noctalia
#include current-theme.conf
# END_KITTY_THEME
allow_remote_control yes
include ~/.cache/wal/colors-kitty.conf
